version: "3.4"
services:
  react-hooks-demo:
    build:
      context: .
      target: base
    container_name: react-hooks
    command: npm start
    ports:
      - "6000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
